version: '3'
services:
  db:
    container_name: postgres
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bookmark
      POSTGRES_PASSWORD: bookmark
      POSTGRES_DB: bookmarks
    volumes: 
      - .dbdata:/var/lib/postgres 
    expose:
      - 5432
